## 아이리스 다중 분류

In [1]:
import pandas as pd
df = pd.read_csv('data/iris.csv')
del df['Id']
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
dataset = df.values
X = dataset[:,0:4].astype(float)
Y_obj = dataset[:,4]
Y_obj[0], Y_obj[50], Y_obj[100]

('Iris-setosa', 'Iris-versicolor', 'Iris-virginica')

In [3]:
X.shape

(150, 4)

In [4]:
from sklearn.preprocessing import LabelEncoder

e = LabelEncoder()
Y = e.fit_transform(Y_obj)

In [5]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
import tensorflow as tf
from tensorflow import keras
# One hot encoding
Y_encoded = keras.utils.to_categorical(Y)
Y_encoded[0], Y_encoded[50], Y_encoded[100]

(array([1., 0., 0.], dtype=float32),
 array([0., 1., 0.], dtype=float32),
 array([0., 0., 1.], dtype=float32))

In [7]:
Y_encoded.shape

(150, 3)

In [8]:
# seed 값 설정
seed = 0
tf.random.set_seed(seed)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = \
    train_test_split(X, Y_encoded, test_size=0.3, 
                     shuffle=True, random_state=seed)

In [10]:
# 딥러닝 모델 설정
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(16, input_shape=(4,), activation='relu'),
    Dense(3, activation='softmax')
])
model.summary()

Using TensorFlow backend.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [11]:
# 모델 컴파일 
model.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

In [12]:
from keras.callbacks import ModelCheckpoint
checkpointer = ModelCheckpoint(filepath="model/iris.hdf5", monitor='val_loss', 
                               verbose=1, save_best_only=True)

In [13]:
# 모델 실행
model.fit(X_train, Y_train, epochs=100, batch_size=30, verbose=2,
          validation_data=(X_test, Y_test), callbacks=[checkpointer]) 

Train on 105 samples, validate on 45 samples
Epoch 1/100
 - 0s - loss: 3.7147 - accuracy: 0.3238 - val_loss: 3.7075 - val_accuracy: 0.3556

Epoch 00001: val_loss improved from inf to 3.70752, saving model to model/iris.hdf5
Epoch 2/100
 - 0s - loss: 3.4761 - accuracy: 0.3238 - val_loss: 3.4953 - val_accuracy: 0.3556

Epoch 00002: val_loss improved from 3.70752 to 3.49528, saving model to model/iris.hdf5
Epoch 3/100
 - 0s - loss: 3.2362 - accuracy: 0.3238 - val_loss: 3.2901 - val_accuracy: 0.3556

Epoch 00003: val_loss improved from 3.49528 to 3.29006, saving model to model/iris.hdf5
Epoch 4/100
 - 0s - loss: 3.0131 - accuracy: 0.3238 - val_loss: 3.0871 - val_accuracy: 0.3556

Epoch 00004: val_loss improved from 3.29006 to 3.08710, saving model to model/iris.hdf5
Epoch 5/100
 - 0s - loss: 2.7945 - accuracy: 0.3238 - val_loss: 2.8952 - val_accuracy: 0.3556

Epoch 00005: val_loss improved from 3.08710 to 2.89515, saving model to model/iris.hdf5
Epoch 6/100
 - 0s - loss: 2.5896 - accuracy:


Epoch 00045: val_loss improved from 0.54011 to 0.53474, saving model to model/iris.hdf5
Epoch 46/100
 - 0s - loss: 0.4708 - accuracy: 0.8667 - val_loss: 0.5254 - val_accuracy: 0.7778

Epoch 00046: val_loss improved from 0.53474 to 0.52544, saving model to model/iris.hdf5
Epoch 47/100
 - 0s - loss: 0.4649 - accuracy: 0.8762 - val_loss: 0.5193 - val_accuracy: 0.7778

Epoch 00047: val_loss improved from 0.52544 to 0.51928, saving model to model/iris.hdf5
Epoch 48/100
 - 0s - loss: 0.4591 - accuracy: 0.8762 - val_loss: 0.5120 - val_accuracy: 0.7778

Epoch 00048: val_loss improved from 0.51928 to 0.51203, saving model to model/iris.hdf5
Epoch 49/100
 - 0s - loss: 0.4536 - accuracy: 0.8762 - val_loss: 0.5058 - val_accuracy: 0.7778

Epoch 00049: val_loss improved from 0.51203 to 0.50585, saving model to model/iris.hdf5
Epoch 50/100
 - 0s - loss: 0.4481 - accuracy: 0.8857 - val_loss: 0.5015 - val_accuracy: 0.7778

Epoch 00050: val_loss improved from 0.50585 to 0.50154, saving model to model/i


Epoch 00090: val_loss improved from 0.35784 to 0.35539, saving model to model/iris.hdf5
Epoch 91/100
 - 0s - loss: 0.3040 - accuracy: 0.9619 - val_loss: 0.3532 - val_accuracy: 0.9333

Epoch 00091: val_loss improved from 0.35539 to 0.35318, saving model to model/iris.hdf5
Epoch 92/100
 - 0s - loss: 0.3015 - accuracy: 0.9619 - val_loss: 0.3499 - val_accuracy: 0.9556

Epoch 00092: val_loss improved from 0.35318 to 0.34992, saving model to model/iris.hdf5
Epoch 93/100
 - 0s - loss: 0.2991 - accuracy: 0.9619 - val_loss: 0.3450 - val_accuracy: 0.9556

Epoch 00093: val_loss improved from 0.34992 to 0.34504, saving model to model/iris.hdf5
Epoch 94/100
 - 0s - loss: 0.2968 - accuracy: 0.9619 - val_loss: 0.3414 - val_accuracy: 0.9778

Epoch 00094: val_loss improved from 0.34504 to 0.34142, saving model to model/iris.hdf5
Epoch 95/100
 - 0s - loss: 0.2949 - accuracy: 0.9619 - val_loss: 0.3373 - val_accuracy: 0.9778

Epoch 00095: val_loss improved from 0.34142 to 0.33727, saving model to model/i

In [20]:
from keras.models import load_model
del model
model = load_model("model/iris.hdf5")

In [21]:
# 결과 출력 
print("\n Accuracy: %.4f" % (model.evaluate(X_test, Y_test, verbose=2)[1])) 


 Accuracy: 0.9556


### Model 2

In [15]:
# 딥러닝 모델 설정
model2 = Sequential([
    Dense(12, input_shape=(4,), activation='relu'),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])
model2.summary() 

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 12)                60        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 191
Trainable params: 191
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 모델 컴파일 
model2.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

In [17]:
checkpointer = ModelCheckpoint(filepath="model/iris2.hdf5", monitor='val_loss', 
                               verbose=1, save_best_only=True)

In [18]:
# 모델 실행
model2.fit(X_train, Y_train, epochs=100, batch_size=30, verbose=2,
           validation_data=(X_test, Y_test), callbacks=[checkpointer]) 

Train on 105 samples, validate on 45 samples
Epoch 1/100
 - 0s - loss: 2.6862 - accuracy: 0.3714 - val_loss: 3.2268 - val_accuracy: 0.2444

Epoch 00001: val_loss improved from inf to 3.22682, saving model to model/iris2.hdf5
Epoch 2/100
 - 0s - loss: 2.4865 - accuracy: 0.3714 - val_loss: 3.0023 - val_accuracy: 0.2444

Epoch 00002: val_loss improved from 3.22682 to 3.00235, saving model to model/iris2.hdf5
Epoch 3/100
 - 0s - loss: 2.3138 - accuracy: 0.3714 - val_loss: 2.7873 - val_accuracy: 0.2444

Epoch 00003: val_loss improved from 3.00235 to 2.78732, saving model to model/iris2.hdf5
Epoch 4/100
 - 0s - loss: 2.1543 - accuracy: 0.3714 - val_loss: 2.5844 - val_accuracy: 0.2444

Epoch 00004: val_loss improved from 2.78732 to 2.58443, saving model to model/iris2.hdf5
Epoch 5/100
 - 0s - loss: 1.9858 - accuracy: 0.3714 - val_loss: 2.3997 - val_accuracy: 0.2444

Epoch 00005: val_loss improved from 2.58443 to 2.39974, saving model to model/iris2.hdf5
Epoch 6/100
 - 0s - loss: 1.8478 - accu


Epoch 00045: val_loss improved from 0.48649 to 0.47023, saving model to model/iris2.hdf5
Epoch 46/100
 - 0s - loss: 0.4111 - accuracy: 0.9524 - val_loss: 0.4593 - val_accuracy: 0.9556

Epoch 00046: val_loss improved from 0.47023 to 0.45934, saving model to model/iris2.hdf5
Epoch 47/100
 - 0s - loss: 0.4028 - accuracy: 0.9524 - val_loss: 0.4502 - val_accuracy: 0.9556

Epoch 00047: val_loss improved from 0.45934 to 0.45021, saving model to model/iris2.hdf5
Epoch 48/100
 - 0s - loss: 0.3948 - accuracy: 0.9524 - val_loss: 0.4450 - val_accuracy: 0.9333

Epoch 00048: val_loss improved from 0.45021 to 0.44495, saving model to model/iris2.hdf5
Epoch 49/100
 - 0s - loss: 0.3869 - accuracy: 0.9524 - val_loss: 0.4382 - val_accuracy: 0.9333

Epoch 00049: val_loss improved from 0.44495 to 0.43822, saving model to model/iris2.hdf5
Epoch 50/100
 - 0s - loss: 0.3795 - accuracy: 0.9524 - val_loss: 0.4243 - val_accuracy: 0.9556

Epoch 00050: val_loss improved from 0.43822 to 0.42431, saving model to mo


Epoch 00092: val_loss improved from 0.23263 to 0.22571, saving model to model/iris2.hdf5
Epoch 93/100
 - 0s - loss: 0.1887 - accuracy: 0.9714 - val_loss: 0.2208 - val_accuracy: 0.9778

Epoch 00093: val_loss improved from 0.22571 to 0.22078, saving model to model/iris2.hdf5
Epoch 94/100
 - 0s - loss: 0.1870 - accuracy: 0.9619 - val_loss: 0.2180 - val_accuracy: 0.9778

Epoch 00094: val_loss improved from 0.22078 to 0.21803, saving model to model/iris2.hdf5
Epoch 95/100
 - 0s - loss: 0.1834 - accuracy: 0.9714 - val_loss: 0.2221 - val_accuracy: 0.9778

Epoch 00095: val_loss did not improve from 0.21803
Epoch 96/100
 - 0s - loss: 0.1810 - accuracy: 0.9619 - val_loss: 0.2291 - val_accuracy: 0.9778

Epoch 00096: val_loss did not improve from 0.21803
Epoch 97/100
 - 0s - loss: 0.1815 - accuracy: 0.9619 - val_loss: 0.2326 - val_accuracy: 0.9556

Epoch 00097: val_loss did not improve from 0.21803
Epoch 98/100
 - 0s - loss: 0.1792 - accuracy: 0.9619 - val_loss: 0.2156 - val_accuracy: 0.9778

Epo

In [22]:
del model2
model2 = load_model("model/iris2.hdf5")

In [23]:
# 결과 출력 
print("\n Accuracy: %.4f" % (model2.evaluate(X_test, Y_test, verbose=2)[1]))


 Accuracy: 0.9778


In [34]:
import numpy as np
iris = np.array([5.6, 3.0, 4.5, 1.5]).reshape(1, 4)
iris

array([[5.6, 3. , 4.5, 1.5]])

In [36]:
res = model2.predict(iris)

In [37]:
np.argmax(res)

1